name: GeneratorPvP
version: ${project.version}
main: me.c10coding.generatorpvp.GeneratorPvP
api-version: 1.13
depend:
  - Vault
  - PlaceholderAPI
commands:
  menu:
    description: "Opens the generator pvp menu"
  genpvp:
    description: "Other commands that may come with the plugin. Primarily admin commands."
    aliases:
      - gp
  leaderboard:
    description: "Opens the leaderboard for GenPvP"
    aliases:
      - lb
  genpvpconfirm:
    description: "For all the commands that have to be confirmed"
    aliases:
      - gpconfirm

permissions:
  gp.purchase.antifall:
    description: "Permissions to purchase the antifall boots"
    default: true
  gp.use:
    description: Allows you to open the plugin menu
    default: true
  gp.teleport.vip:
    default: op
  gp.teleport.mvp:
    default: op
  gp.teleport.ultra:
    default: op
  gp.teleport.special:
    description: "Allows you to use the special warp"
    default: true
  gp.purchase.gray:
    description: "Allows you to purchase the gray chat color"
    default: true
  gp.purchase.limegreen:
    description: "Allows you to purchase the lime green chat color"
    default: true
  gp.purchase.yellow:
    description: "Allows you to purchase the yellow chat color"
    default: true
  gp.purchase.blue:
    description: "Allows you to purchase the blue chat color"
    default: op
  gp.purchase.gold:
    description: "Allows you to purchase the gold chat color"
    default: op
  gp.purchase.lightpurple:
    description: "Allows you to purchase the light purple chat color"
    default: op
  gp.unlock.gray:
    default: op
  gp.unlock.blue:
    default: op
  gp.unlock.gold:
    default: op
  gp.unlock.lightpurple:
    default: op
  gp.unlock.limegreen:
    default: op
  gp.unlock.yellow:
    default: op


  gp.purchase.strength:
    default: op
  gp.purchase.regen:
    default: true
  gp.purchase.glowing:
    default: true
  gp.purchase.speed:
    default: true
  gp.purchase.jumpboost:
    default: op
  gp.purchase.doublejump:
    default: true
  gp.purchase.absorption:
    default: true
  gp.purchase.blindness:
    default: true
  gp.purchase.coin:
    default: op
  gp.purchase.antikb:
    default: true
  gp.purchase.stonks:
    default: true
  gp.purchase.levitation:
    default: true
  gp.purchase.invisibility:
    default: true

  gp.unlock.antifall:
    default: op
  gp.unlock.strength:
    default: op
  gp.unlock.regen:
    default: op
  gp.unlock.glowing:
    default: op
  gp.unlock.speed:
    default: op
  gp.unlock.jumpboost:
    default: op
  gp.unlock.doublejump:
    default: op
  gp.unlock.absorption:
    default: op
  gp.unlock.blindness:
    default: op
  gp.unlock.coin:
    default: op
  gp.unlock.antikb:
    default: op
  gp.unlock.stonks:
    default: op
  gp.unlock.levitation:
    default: op
  gp.unlock.invisibility:
    default: op




