name: GeneratorPvP
version: ${project.version}
main: me.c10coding.generatorpvp.GeneratorPvP
api-version: 1.13
commands:
  menu:
    description: "Opens the generator pvp menu"
  genpvp:
    description: "Other commands that may come with the plugin. Primarily admin commands."
    aliases:
      - gp

permissions:
  gp.*:
    description: Gives access to all GeneratorPvP commands and what-not
    children:
      gp.teleport.vip: true
      gp.teleport.mvp: true
      gp.teleport.ultra: true
      gp.teleport.special: true
    default: op
  gp.use:
    description: Allows you to open the plugin menu
    default: true
  gp.teleport.vip:
    default: op
  gp.teleport.mvp:
    default: op
  gp.teleport.ultra:
    default: op
  gp.teleport.special:
    default: op
  #Whether a player can purchase the color or not
  gp.purchase.gray:
    default: true
  gp.purchase.green:
    default: true
  gp.purchase.yellow:
    default: true
  gp.purchase.blue:
    default: op
  gp.purchase.gold:
    default: op
  gp.purchase.pink:
    default: op
  #If they have this permission, they already have the chat color purchased
  gp.unlock.gray:
    default: op
  gp.unlock.blue:
    default: op
  gp.unlock.gold:
    default: op
  gp.unlock.purple:
    default: op
  gp.unlock.green:
    default: op
  gp.unlock.yellow:
    default: op


